POST http://localhost:4000
Content-Type: application/json

{
  "ref": "development",
  "stateId": "1234",
  "signature": "",
  "eventName": "issues.closed",
  "action": "closed",
  "command": null,
  "settings": {
    "evmPrivateEncrypted": "YfEnpznMNbSPhCQzWy1Uevi4xQC25SqJrHd87CjjS1gsu92QrCReSgvl8Z_pVI1ZM57PNC1mZSgHbNgX9ITmOJc6qaOJ_mRe_sP_8jBcNimusDCQcWEkcPIW7Md-QGDPnwuN8FIavS7I0uiOIRYK6h0NK02-3uzPqhM",
    "incentives": {
      "userExtractor": {},
      "dataPurge": {},
      "formattingEvaluator": {},
      "contentEvaluator": {},
      "payment": {},
      "githubComment": {
        "post": false,
        "debug": true
      }
    }
  },
  "authToken": "{{GITHUB_TOKEN}}",
  "eventPayload": {
    "issue": {
      "state_reason": "completed",
      "url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/{{ISSUE_ID}}",
      "repository_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}",
      "labels_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/{{ISSUE_ID}}/labels{/name}",
      "comments_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/{{ISSUE_ID}}/comments",
      "events_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/{{ISSUE_ID}}/events",
      "html_url": "https://github.com/{{OWNER}}/{{REPO}}/issues/{{ISSUE_ID}}",
      "id": 1,
      "node_id": "MDU6SXNzdWUx",
      "number": 1,
      "title": "Found a bug",
      "user": {
        "login": "{{OWNER}}",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/{{OWNER}}_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/{{OWNER}}",
        "html_url": "https://github.com/{{OWNER}}",
        "followers_url": "https://api.github.com/users/{{OWNER}}/followers",
        "following_url": "https://api.github.com/users/{{OWNER}}/following{/other_user}",
        "gists_url": "https://api.github.com/users/{{OWNER}}/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/{{OWNER}}/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/{{OWNER}}/subscriptions",
        "organizations_url": "https://api.github.com/users/{{OWNER}}/orgs",
        "repos_url": "https://api.github.com/users/{{OWNER}}/repos",
        "events_url": "https://api.github.com/users/{{OWNER}}/events{/privacy}",
        "received_events_url": "https://api.github.com/users/{{OWNER}}/received_events",
        "type": "User",
        "site_admin": false
      },
      "state": "closed",
      "locked": false,
      "assignee": {
        "login": "{{OWNER}}",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/{{OWNER}}_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/{{OWNER}}",
        "html_url": "https://github.com/{{OWNER}}",
        "followers_url": "https://api.github.com/users/{{OWNER}}/followers",
        "following_url": "https://api.github.com/users/{{OWNER}}/following{/other_user}",
        "gists_url": "https://api.github.com/users/{{OWNER}}/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/{{OWNER}}/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/{{OWNER}}/subscriptions",
        "organizations_url": "https://api.github.com/users/{{OWNER}}/orgs",
        "repos_url": "https://api.github.com/users/{{OWNER}}/repos",
        "events_url": "https://api.github.com/users/{{OWNER}}/events{/privacy}",
        "received_events_url": "https://api.github.com/users/{{OWNER}}/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 208045946,
          "node_id": "MDU6TGFiZWwyMDgwNDU5NDY=",
          "url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/labels/bug",
          "name": "bug",
          "description": "Something isn't working",
          "color": "f29513",
          "default": true
        }
      ],
      "comments": 0,
      "created_at": "2011-04-22T13:33:48Z",
      "updated_at": "2011-04-22T13:33:48Z",
      "closed_at": "2011-04-22T13:33:48Z",
      "author_association": "OWNER",
      "body": "I'm having a problem with this."
    },
    "repository": {
      "id": 1296269,
      "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
      "name": "{{REPO}}",
      "full_name": "{{OWNER}}/{{REPO}}",
      "owner": {
        "login": "{{OWNER}}",
        "id": 159901852,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": "https://github.com/images/error/{{OWNER}}_happy.gif",
        "gravatar_id": "",
        "url": "https://api.github.com/users/{{OWNER}}",
        "html_url": "https://github.com/{{OWNER}}",
        "followers_url": "https://api.github.com/users/{{OWNER}}/followers",
        "following_url": "https://api.github.com/users/{{OWNER}}/following{/other_user}",
        "gists_url": "https://api.github.com/users/{{OWNER}}/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/{{OWNER}}/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/{{OWNER}}/subscriptions",
        "organizations_url": "https://api.github.com/users/{{OWNER}}/orgs",
        "repos_url": "https://api.github.com/users/{{OWNER}}/repos",
        "events_url": "https://api.github.com/users/{{OWNER}}/events{/privacy}",
        "received_events_url": "https://api.github.com/users/{{OWNER}}/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/{{OWNER}}/{{REPO}}",
      "description": "This your first repo!",
      "fork": false,
      "url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}",
      "archive_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/{archive_format}{/ref}",
      "assignees_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/assignees{/user}",
      "blobs_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/git/blobs{/sha}",
      "branches_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/branches{/branch}",
      "collaborators_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/collaborators{/collaborator}",
      "comments_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/comments{/number}",
      "commits_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/commits{/sha}",
      "compare_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/compare/{base}...{head}",
      "contents_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/contents/{+path}",
      "contributors_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/contributors",
      "deployments_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/deployments",
      "downloads_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/downloads",
      "events_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/events",
      "forks_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/forks",
      "git_commits_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/git/commits{/sha}",
      "git_refs_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/git/refs{/sha}",
      "git_tags_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/git/tags{/sha}",
      "git_url": "git:github.com/{{OWNER}}/{{REPO}}.git",
      "issue_comment_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/comments{/number}",
      "issue_events_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues/events{/number}",
      "issues_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/issues{/number}",
      "keys_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/keys{/key_id}",
      "labels_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/labels{/name}",
      "languages_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/languages",
      "merges_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/merges",
      "milestones_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/notifications{?since,all,participating}",
      "pulls_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/pulls{/number}",
      "releases_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/releases{/id}",
      "stargazers_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/stargazers",
      "statuses_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/statuses/{sha}",
      "subscribers_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/subscribers",
      "subscription_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/subscription",
      "tags_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/tags",
      "teams_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/teams",
      "trees_url": "https://api.github.com/repos/{{OWNER}}/{{REPO}}/git/trees{/sha}",
      "homepage": "https://github.com",
      "language": null,
      "forks_count": 9,
      "stargazers_count": 80,
      "watchers_count": 80,
      "size": 108,
      "default_branch": "master",
      "open_issues_count": 0,
      "is_template": false,
      "topics": [],
      "has_issues": true,
      "has_projects": true,
      "has_wiki": true,
      "has_pages": false,
      "has_downloads": true,
      "archived": false,
      "disabled": false,
      "visibility": "public",
      "pushed_at": "2011-01-26T19:06:43Z",
      "created_at": "2011-01-26T19:01:12Z",
      "updated_at": "2011-01-26T19:14:43Z",
      "permissions": {
        "admin": false,
        "maintain": false,
        "push": false,
        "triage": false,
        "pull": true
      },
      "allow_rebase_merge": true,
      "temp_clone_token": "",
      "allow_squash_merge": true,
      "allow_auto_merge": false,
      "delete_branch_on_merge": true,
      "allow_merge_commit": true,
      "subscribers_count": 42,
      "network_count": 0
    },
    "sender": {
      "login": "{{OWNER}}",
      "id": 159901852,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/{{OWNER}}_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/{{OWNER}}",
      "html_url": "https://github.com/{{OWNER}}",
      "followers_url": "https://api.github.com/users/{{OWNER}}/followers",
      "following_url": "https://api.github.com/users/{{OWNER}}/following{/other_user}",
      "gists_url": "https://api.github.com/users/{{OWNER}}/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/{{OWNER}}/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/{{OWNER}}/subscriptions",
      "organizations_url": "https://api.github.com/users/{{OWNER}}/orgs",
      "repos_url": "https://api.github.com/users/{{OWNER}}/repos",
      "events_url": "https://api.github.com/users/{{OWNER}}/events{/privacy}",
      "received_events_url": "https://api.github.com/users/{{OWNER}}/received_events",
      "type": "User",
      "site_admin": false
    }
  }
}