zeroTrue: &zeroTrue
  score: 0
  countWords: true

zeroFalse: &zeroFalse
  score: 0
  countWords: false

oneTrue: &oneTrue
  score: 1
  countWords: true

oneFalse: &oneFalse
  score: 1
  countWords: false

tcrHtmlConfig: &tcrHtmlConfig
  a: *oneTrue
  code: *oneFalse
  img: *oneFalse
  h1: *oneTrue
  h2: *oneTrue
  h3: *oneTrue
  h4: *oneTrue
  h5: *oneTrue
  h6: *oneTrue
  br: *zeroTrue
  p: *zeroTrue
  em: *zeroTrue
  ul: *zeroTrue
  td: *zeroTrue
  hr: *zeroTrue
  ol: *zeroTrue
  pre: *zeroFalse
  strong: *zeroFalse
  blockquote: *zeroFalse
  li:
    score: 0.1
    countWords: true

evmPrivateEncrypted: "0x00"
rewards:
  evmNetworkId: 100
  evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ"
  erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"

incentives:
  payment:
    automaticTransferMode: false
  requirePriceLabel: "auto"
  externalContent:
    llmImageModel:
      model: meta-llama/llama-3.2-11b-vision-instruct:free
    llmWebsiteModel:
      model: deepseek/deepseek-chat-v3-0324:free
  contentEvaluator:
    openAi:
      endpoint: https://openrouter.ai/api/v1
      model: deepseek/deepseek-chat-v3-0324
  userExtractor:
    redeemTask: true
  dataPurge:
    skipCommentsWhileAssigned: all
  formattingEvaluator:
    multipliers:
      - role:
          - ISSUE_AUTHOR
          - ISSUE_COLLABORATOR
          - ISSUE_SPECIFICATION
          - PULL_COLLABORATOR
        multiplier: 1
        rewards:
          wordValue: 0.1
          html: *tcrHtmlConfig

      - role:
          - ISSUE_ASSIGNEE
          - ISSUE_CONTRIBUTOR
        multiplier: 0.25
        rewards:
          wordValue: 0.1
          html: *tcrHtmlConfig

      - role:
          - PULL_AUTHOR
          - PULL_CONTRIBUTOR
          - PULL_ASSIGNEE
          - PULL_SPECIFICATION
        multiplier: 0
        rewards:
          wordValue: 0
          html: *tcrHtmlConfig
  reviewIncentivizer: {}
  simplificationIncentivizer: {}
  githubComment:
    post: false
    debug: false
