# This file serves as a base to build a custom configuration

incentives:
  contentEvaluator: {}
  userExtractor: {}
  dataPurge: {}
  formattingEvaluator: {}
  permitGeneration: {}
  reviewIncentivizer: {}
  githubComment:
    post: false
    debug: false
