# This file serves as a base to build a custom configuration
evmNetworkId: 100
evmPrivateEncrypted: "giLxu7IVSTpEFO89DaeCgnkKemYf2aFlK9EUQkbt71YmFOcQdIkCT8JDpX5zV5Sg1TqBeziZ486U0E3a6nD3emg0x9oeG3ILRUTlOE4I3RBZ0yTadsnV4RvewJMCMZJaYDuom-rHzog8p9InBwaHBszFeWItttSwS7o" # https://github.com/ubiquibot/conversation-rewards/pull/111#issuecomment-2348639931
erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
incentives:
  requirePriceLabel: true
  contentEvaluator:
    enabled: true
    openAi:
      endpoint: https://openrouter.ai/api/v1
    multipliers:
      - role:
          - "ISSUE_SPECIFICATION"
        relevance: 1
  userExtractor:
    redeemTask: true
  dataPurge:
    enabled: true
  reviewIncentivizer:
    baseRate: 100
    conclusiveReviewCredit: 25
  formattingEvaluator:
    multipliers:
      - role:
          - ISSUE_SPECIFICATION
        multiplier: 1
        rewards:
          wordValue: 0.1
          html:
            br:
              score: 0
              countWords: true
            code:
              score: 5
              countWords: false
            p:
              score: 0
              countWords: true
            em:
              score: 0
              countWords: true
            img:
              score: 5
              countWords: true
            strong:
              score: 0
              countWords: false
            blockquote:
              score: 0
              countWords: false
            h1:
              score: 1
              countWords: true
            h2:
              score: 1
              countWords: true
            h3:
              score: 1
              countWords: true
            h4:
              score: 1
              countWords: true
            h5:
              score: 1
              countWords: true
            h6:
              score: 1
              countWords: true
            a:
              score: 5
              countWords: true
            li:
              score: 0.1
              countWords: true
            ul:
              score: 0
              countWords: true
            td:
              score: 0
              countWords: true
            hr:
              score: 0
              countWords: true
            pre:
              score: 0
              countWords: false
            ol:
              score: 0
              countWords: true
      - role:
          - ISSUE_AUTHOR
          - ISSUE_COLLABORATOR
          - PULL_COLLABORATOR
        multiplier: 1
        rewards:
          wordValue: 0.1
          html:
            br:
              score: 0
              countWords: true
            code:
              score: 5
              countWords: false
            p:
              score: 0
              countWords: true
            em:
              score: 0
              countWords: true
            img:
              score: 5
              countWords: true
            strong:
              score: 0
              countWords: false
            blockquote:
              score: 0
              countWords: false
            h1:
              score: 1
              countWords: true
            h2:
              score: 1
              countWords: true
            h3:
              score: 1
              countWords: true
            h4:
              score: 1
              countWords: true
            h5:
              score: 1
              countWords: true
            h6:
              score: 1
              countWords: true
            a:
              score: 5
              countWords: true
            li:
              score: 0.1
              countWords: true
            ul:
              score: 0
              countWords: true
            td:
              score: 0
              countWords: true
            hr:
              score: 0
              countWords: true
            pre:
              score: 0
              countWords: false
            ol:
              score: 0
              countWords: true
      - role:
          - ISSUE_CONTRIBUTOR
          - ISSUE_ASSIGNEE
        multiplier: 0.25
        rewards:
          wordValue: 0.1
          html:
            br:
              score: 0
              countWords: true
            code:
              score: 5
              countWords: false
            p:
              score: 0
              countWords: true
            em:
              score: 0
              countWords: true
            img:
              score: 5
              countWords: true
            strong:
              score: 0
              countWords: false
            blockquote:
              score: 0
              countWords: false
            h1:
              score: 1
              countWords: true
            h2:
              score: 1
              countWords: true
            h3:
              score: 1
              countWords: true
            h4:
              score: 1
              countWords: true
            h5:
              score: 1
              countWords: true
            h6:
              score: 1
              countWords: true
            a:
              score: 5
              countWords: true
            li:
              score: 0.1
              countWords: true
            ul:
              score: 0
              countWords: true
            td:
              score: 0
              countWords: true
            hr:
              score: 0
              countWords: true
            pre:
              score: 0
              countWords: false
            ol:
              score: 0
              countWords: true
      - role:
          - PULL_SPECIFICATION
          - PULL_AUTHOR
          - PULL_ASSIGNEE
          - PULL_CONTRIBUTOR
        multiplier: 0
        rewards:
          wordValue: 0
          html:
            br:
              score: 0
              countWords: true
            code:
              score: 5
              countWords: false
            p:
              score: 0
              countWords: true
            em:
              score: 0
              countWords: true
            img:
              score: 5
              countWords: true
            strong:
              score: 0
              countWords: false
            blockquote:
              score: 0
              countWords: false
            h1:
              score: 1
              countWords: true
            h2:
              score: 1
              countWords: true
            h3:
              score: 1
              countWords: true
            h4:
              score: 1
              countWords: true
            h5:
              score: 1
              countWords: true
            h6:
              score: 1
              countWords: true
            a:
              score: 5
              countWords: true
            li:
              score: 0.1
              countWords: true
            ul:
              score: 0
              countWords: true
            td:
              score: 0
              countWords: true
            hr:
              score: 0
              countWords: true
            pre:
              score: 0
              countWords: false
            ol:
              score: 0
              countWords: true
    wordCountExponent: 0.85
dataCollection:
  maxAttempts: 10
  delayMs: 1000
