name: Formatting Checks

on:
  push:
  pull_request:

jobs:
  spellcheck:
    name: Check for formatting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run formatting checks
        run: |
          bun install
          bun eslint --fix-dry-run --ignore-pattern dist/
          bun format:cspell
          bun prettier --check .
